// ─────────────────────────────────────────────────────────────
// data.js — Données statiques : équipes, alias, groupes, matchs
// ─────────────────────────────────────────────────────────────

export const GROUPS_SEED = [
  { id: 'colleagues', name: 'Collègues', paidEntry: true },
  { id: 'family',     name: 'Famille',   paidEntry: false }
];

// Clé interne → [nom FR, code pays flagcdn, trigramme]
export const TEAMS = {
  Mexico:            ['Mexique',            'mx',     'MEX'],
  SouthAfrica:       ['Afrique du Sud',     'za',     'RSA'],
  SouthKorea:        ['Corée du Sud',       'kr',     'KOR'],
  CzechRepublic:     ['Tchéquie',           'cz',     'CZE'],
  Canada:            ['Canada',             'ca',     'CAN'],
  BosniaHerzegovina: ['Bosnie-Herzégovine', 'ba',     'BIH'],
  USA:               ['États-Unis',         'us',     'USA'],
  Paraguay:          ['Paraguay',           'py',     'PAR'],
  Qatar:             ['Qatar',              'qa',     'QAT'],
  Switzerland:       ['Suisse',             'ch',     'SUI'],
  Brazil:            ['Brésil',             'br',     'BRA'],
  Morocco:           ['Maroc',              'ma',     'MAR'],
  Haiti:             ['Haïti',              'ht',     'HAI'],
  Scotland:          ['Écosse',             'gb-sct', 'SCO'],
  Australia:         ['Australie',          'au',     'AUS'],
  Turkey:            ['Turquie',            'tr',     'TUR'],
  Germany:           ['Allemagne',          'de',     'GER'],
  Curacao:           ['Curaçao',            'cw',     'CUW'],
  Netherlands:       ['Pays-Bas',           'nl',     'NED'],
  Japan:             ['Japon',              'jp',     'JPN'],
  IvoryCoast:        ["Côte d'Ivoire",      'ci',     'CIV'],
  Ecuador:           ['Équateur',           'ec',     'ECU'],
  Sweden:            ['Suède',              'se',     'SWE'],
  Tunisia:           ['Tunisie',            'tn',     'TUN'],
  Spain:             ['Espagne',            'es',     'ESP'],
  CapeVerde:         ['Cap-Vert',           'cv',     'CPV'],
  Belgium:           ['Belgique',           'be',     'BEL'],
  Egypt:             ['Égypte',             'eg',     'EGY'],
  SaudiArabia:       ['Arabie saoudite',    'sa',     'KSA'],
  Uruguay:           ['Uruguay',            'uy',     'URU'],
  Iran:              ['Iran',               'ir',     'IRN'],
  NewZealand:        ['Nouvelle-Zélande',   'nz',     'NZL'],
  France:            ['France',             'fr',     'FRA'],
  Senegal:           ['Sénégal',            'sn',     'SEN'],
  Iraq:              ['Irak',               'iq',     'IRQ'],
  Norway:            ['Norvège',            'no',     'NOR'],
  Argentina:         ['Argentine',          'ar',     'ARG'],
  Algeria:           ['Algérie',            'dz',     'ALG'],
  Austria:           ['Autriche',           'at',     'AUT'],
  Jordan:            ['Jordanie',           'jo',     'JOR'],
  Portugal:          ['Portugal',           'pt',     'POR'],
  DRCongo:           ['RD Congo',           'cd',     'COD'],
  England:           ['Angleterre',         'gb-eng', 'ENG'],
  Croatia:           ['Croatie',            'hr',     'CRO'],
  Ghana:             ['Ghana',              'gh',     'GHA'],
  Panama:            ['Panama',             'pa',     'PAN'],
  Uzbekistan:        ['Ouzbékistan',        'uz',     'UZB'],
  Colombia:          ['Colombie',           'co',     'COL'],
};

// Alias pour la saisie manuelle en français → clé interne
export const ALIAS = {
  Mexique:             'Mexico',
  France:              'France',
  Bresil:              'Brazil',
  'Brésil':            'Brazil',
  Maroc:               'Morocco',
  Suisse:              'Switzerland',
  Belgique:            'Belgium',
  Espagne:             'Spain',
  Portugal:            'Portugal',
  Argentine:           'Argentina',
  Allemagne:           'Germany',
  'Afrique du Sud':    'SouthAfrica',
  'Corée du Sud':      'SouthKorea',
  'Coree du Sud':      'SouthKorea',
  Tchequie:            'CzechRepublic',
  'Tchéquie':          'CzechRepublic',
  'Bosnie-Herzégovine':'BosniaHerzegovina',
  'États-Unis':        'USA',
  'Etats-Unis':        'USA',
  'Haïti':             'Haiti',
  'Écosse':            'Scotland',
  Ecosse:              'Scotland',
  Australie:           'Australia',
  Turquie:             'Turkey',
  'Curaçao':           'Curacao',
  'Pays-Bas':          'Netherlands',
  Japon:               'Japan',
  "Côte d'Ivoire":     'IvoryCoast',
  'Cote d Ivoire':     'IvoryCoast',
  Equateur:            'Ecuador',
  'Équateur':          'Ecuador',
  'Suède':             'Sweden',
  Tunisie:             'Tunisia',
  'Cap-Vert':          'CapeVerde',
  'Égypte':            'Egypt',
  'Arabie saoudite':   'SaudiArabia',
  'Nouvelle-Zélande':  'NewZealand',
  'Sénégal':           'Senegal',
  Irak:                'Iraq',
  'Norvège':           'Norway',
  'Algérie':           'Algeria',
  Autriche:            'Austria',
  Jordanie:            'Jordan',
  'RD Congo':          'DRCongo',
  Angleterre:          'England',
  Croatie:             'Croatia',
  Ouzbekistan:         'Uzbekistan',
  'Ouzbékistan':       'Uzbekistan',
  Colombie:            'Colombia',
};

// Calendrier des phases de groupes [date, groupe, équipeA, équipeB]
export const MATCH_SEED = [
  ['2026-06-11','A','Mexico','SouthAfrica'],
  ['2026-06-12','A','SouthKorea','CzechRepublic'],
  ['2026-06-12','B','Canada','BosniaHerzegovina'],
  ['2026-06-13','D','USA','Paraguay'],
  ['2026-06-13','B','Qatar','Switzerland'],
  ['2026-06-13','C','Brazil','Morocco'],
  ['2026-06-14','C','Haiti','Scotland'],
  ['2026-06-14','D','Australia','Turkey'],
  ['2026-06-14','E','Germany','Curacao'],
  ['2026-06-14','F','Netherlands','Japan'],
  ['2026-06-15','E','IvoryCoast','Ecuador'],
  ['2026-06-15','F','Sweden','Tunisia'],
  ['2026-06-15','H','Spain','CapeVerde'],
  ['2026-06-15','G','Belgium','Egypt'],
  ['2026-06-15','H','SaudiArabia','Uruguay'],
  ['2026-06-16','G','Iran','NewZealand'],
  ['2026-06-16','I','France','Senegal'],
  ['2026-06-16','I','Iraq','Norway'],
  ['2026-06-17','J','Argentina','Algeria'],
  ['2026-06-17','J','Austria','Jordan'],
  ['2026-06-17','K','Portugal','DRCongo'],
  ['2026-06-17','L','England','Croatia'],
  ['2026-06-18','L','Ghana','Panama'],
  ['2026-06-18','K','Uzbekistan','Colombia'],
  ['2026-06-18','A','CzechRepublic','SouthAfrica'],
  ['2026-06-18','B','Switzerland','BosniaHerzegovina'],
  ['2026-06-18','B','Canada','Qatar'],
  ['2026-06-19','A','Mexico','SouthKorea'],
  ['2026-06-19','D','USA','Australia'],
  ['2026-06-19','C','Scotland','Morocco'],
  ['2026-06-20','C','Brazil','Haiti'],
  ['2026-06-20','D','Turkey','Paraguay'],
  ['2026-06-20','F','Netherlands','Sweden'],
  ['2026-06-20','E','Germany','IvoryCoast'],
  ['2026-06-21','E','Ecuador','Curacao'],
  ['2026-06-21','F','Tunisia','Japan'],
  ['2026-06-21','H','Spain','SaudiArabia'],
  ['2026-06-21','G','Belgium','Iran'],
  ['2026-06-21','H','Uruguay','CapeVerde'],
  ['2026-06-22','G','NewZealand','Egypt'],
  ['2026-06-22','J','Argentina','Austria'],
  ['2026-06-22','I','France','Iraq'],
  ['2026-06-23','I','Norway','Senegal'],
  ['2026-06-23','J','Jordan','Algeria'],
  ['2026-06-23','K','Portugal','Uzbekistan'],
  ['2026-06-23','L','England','Ghana'],
  ['2026-06-24','L','Panama','Croatia'],
  ['2026-06-24','K','Colombia','DRCongo'],
  ['2026-06-24','B','Switzerland','Canada'],
  ['2026-06-24','B','BosniaHerzegovina','Qatar'],
  ['2026-06-24','C','Morocco','Haiti'],
  ['2026-06-24','C','Scotland','Brazil'],
  ['2026-06-25','A','SouthAfrica','SouthKorea'],
  ['2026-06-25','A','CzechRepublic','Mexico'],
  ['2026-06-25','E','Curacao','IvoryCoast'],
  ['2026-06-25','E','Ecuador','Germany'],
  ['2026-06-26','F','Tunisia','Netherlands'],
  ['2026-06-26','F','Japan','Sweden'],
  ['2026-06-26','D','Turkey','USA'],
  ['2026-06-26','D','Paraguay','Australia'],
  ['2026-06-26','I','Norway','France'],
  ['2026-06-26','I','Senegal','Iraq'],
  ['2026-06-27','H','CapeVerde','SaudiArabia'],
  ['2026-06-27','H','Uruguay','Spain'],
  ['2026-06-27','G','NewZealand','Belgium'],
  ['2026-06-27','G','Egypt','Iran'],
  ['2026-06-27','L','Panama','England'],
  ['2026-06-27','L','Croatia','Ghana'],
  ['2026-06-28','K','Colombia','Portugal'],
  ['2026-06-28','K','DRCongo','Uzbekistan'],
  ['2026-06-28','J','Algeria','Austria'],
  ['2026-06-28','J','Jordan','Argentina'],
];

// Phases du tableau final [id, label, nb matchs]
export const KO_STAGES = [
  ['r32',   '16es de finale', 16],
  ['r16',   '8es de finale',   8],
  ['qf',    'Quarts',          4],
  ['sf',    'Demi-finales',    2],
  ['final', 'Finale',          1],
];
